feat: Adds and refactors for Triton FIL examples
kserve/modelmesh-minio-examples pull request #7
Opened 2024-01-26 20:51 UTC by rafvasq

Related to https://github.com/kserve/modelmesh-serving/pull/484, this PR expands on `lightgbm` and `xgboost` example models to show that they can be deployed with Triton (in addition to MLServer).

2024-02-27 17:44 UTC, ckadner requested changes
Thanks @rafvasq -- just 2 little nits

2024-02-27 17:44 UTC, ckadner commented on lightgbm/lightgbm-fil/config.pbtxt
> +]
"No newline at end of file" ⛔

2024-02-27 17:44 UTC, ckadner commented on xgboost/mushroom-fil/config.pbtxt
> +]
"No newline at end of file" ⛔

2024-02-28 20:28 UTC, rafvasq commented on xgboost/mushroom-fil/config.pbtxt
> +]
Thanks Christian, I took care of these.

2024-03-05 17:09 UTC, ckadner approved these changes
/lgtm

2024-03-05 17:50 UTC, ckadner commented
/approve

2024-03-05 17:53 UTC, ckadner approved these changes
/lgtm
/approve

2024-03-05 20:01 UTC, merged

2024-03-05 20:03 UTC, ckadner commented
Thanks @rafvasq